name: Test Conductor Laravel

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8, 8.0.2, 8.1]
        composer: [2]
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          PHP_VERSION=${{ matrix.php }} COMPOSER_VERSION=${{ matrix.composer }} \
          docker-compose up --force-recreate --build --exit-code-from=validation
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "*.junit.xml"
          name: test-reports-${{ matrix.php }}
          if-no-files-found: error
